# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_region_code', models.CharField(max_length=10, verbose_name='country_region_code')),
                ('country_region_name', models.CharField(max_length=30, verbose_name='country_region_name')),
                ('country_region_py_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='country_region_py_code')),
                ('country_region_quanpin', models.CharField(blank=True, max_length=200, null=True, verbose_name='country_region_quanpin')),
                ('state_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='state_code')),
                ('state_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='state_name')),
                ('state_py_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='state_py_code')),
                ('state_quanpin', models.CharField(blank=True, max_length=200, null=True, verbose_name='state_quanpin')),
                ('city_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='city_code')),
                ('city_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='city_name')),
                ('city_py_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='city_py_code')),
                ('city_quanpin', models.CharField(blank=True, max_length=200, null=True, verbose_name='city_quanpin')),
                ('region_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='region_code')),
                ('region_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='region_name')),
                ('region_py_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='region_py_code')),
                ('region_quanpin', models.CharField(blank=True, max_length=200, null=True, verbose_name='region_quanpin')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('detail_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='detail_location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('pinyin', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='brand')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='old_price')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='is_bestseller')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='meta keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='meta description')),
                ('manufacturer', models.CharField(blank=True, max_length=300, verbose_name='manufacturer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MerchandisePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('pinyin', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='merchandise_photo', verbose_name='image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_to_merchandise', to='order_manage.Merchandise')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.PositiveSmallIntegerField(default=1, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='price')),
                ('payment', models.CharField(choices=[('hdfk', 'hdfk'), ('zfb', 'zhifubao'), ('wx', 'weixin')], default='', max_length=50, verbose_name='payment')),
                ('buyer', models.CharField(default='zhangsan', max_length=100, verbose_name='buyer')),
                ('cell_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='cell_phone')),
                ('state', models.CharField(blank=True, default='', max_length=50, verbose_name='state')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='city')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='region')),
                ('address', models.CharField(default='', max_length=300, verbose_name='address')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='comment')),
                ('status', models.CharField(choices=[('0', 'xiadan'), ('-1', 'chedan'), ('1', 'yifahuo'), ('2', 'yishouhuo'), ('3', 'yijiesuan')], default='', max_length=5, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('express', models.CharField(choices=[('sf', 'shunfeng'), ('ems', 'ems'), ('zt', 'zhongtong'), ('yt', 'yuantong'), ('yd', 'yunda'), ('bsht', 'baishihuitong'), ('ttkd', 'tiantiankuaidi'), ('st', 'shentong')], default='', max_length=50, verbose_name='express')),
                ('express_no', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='express_no')),
                ('express_info', models.TextField(blank=True, null=True, verbose_name='express_info')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_merchandise', to='order_manage.Merchandise')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip', models.GenericIPAddressField(verbose_name='from_ip')),
                ('visit_url', models.URLField(verbose_name='visit_url')),
                ('visit_date', models.DateTimeField(null=True)),
                ('browser', models.CharField(blank=True, max_length=64, null=True, verbose_name='browser')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TourLog',
                'verbose_name_plural': 'TourLogs',
            },
        ),
        migrations.AlterIndexTogether(
            name='location',
            index_together=set([('country_region_code', 'state_code', 'city_code', 'region_code')]),
        ),
    ]
