# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0003_auto_20170529_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True, verbose_name='meta keywords'),
        ),
    ]
