# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0004_auto_20170529_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='highlighted',
            field=models.TextField(default='laksdj'),
            preserve_default=False,
        ),
    ]
