# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0006_auto_20170604_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='express',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='express_company', to='order_manage.Express', to_field='code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='order_manage.Payment', to_field='code'),
        ),
    ]
