# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0007_auto_20170605_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, verbose_name='city'),
        ),
    ]
