# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0008_auto_20170605_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='order',
            index_together=set([('title', 'created_at', 'express_no')]),
        ),
    ]
