# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0009_auto_20170606_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandisepicture',
            options={'ordering': ('merchandise', 'order')},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ('visit_date', 'from_ip'), 'verbose_name': 'VisitLog', 'verbose_name_plural': 'VisitLogs'},
        ),
        migrations.AddField(
            model_name='merchandisepicture',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description                                         meta tag', max_length=255, null=True, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of                                      SEO keywords for meta tag', max_length=255, null=True, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_manage.Express', to_field='code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_manage.Merchandise'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_manage.Payment', to_field='code'),
        ),
    ]
