# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0010_auto_20170607_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandisepicture',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='order_manage.Merchandise'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_manage.OrderStatus'),
        ),
    ]
