# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0011_auto_20170607_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_manage.OrderStatus'),
        ),
    ]
